//! Tier 1: Parity golden tests — compare Rust output against Python-generated expected files.
//!
//! These tests always run in CI (no external dependencies). The expected files were
//! generated by `scripts/generate-parity-golden.sh` using the pinned Python flowmark version.
//!
//! On failure, writes `.actual.*.md` files next to the expected files for easy diffing.
//!
//! See: tests/parity/corner-cases.md
#![allow(clippy::unwrap_used)]

use flowmark::config::ListSpacing;
use flowmark::fill_markdown;
use std::path::Path;

#[allow(clippy::struct_excessive_bools)]
struct GoldenTest {
    input_file: &'static str,
    expected_file: &'static str,
    mode_name: &'static str,
    semantic: bool,
    cleanups: bool,
    smartquotes: bool,
    ellipses: bool,
    plaintext: bool,
    list_spacing: ListSpacing,
}

fn run_parity_golden(t: &GoldenTest) {
    let parity_dir = Path::new("tests/parity");
    let input = std::fs::read_to_string(parity_dir.join(t.input_file))
        .unwrap_or_else(|_| panic!("Failed to read input: {}", t.input_file));
    let expected = std::fs::read_to_string(parity_dir.join(t.expected_file))
        .unwrap_or_else(|_| panic!("Failed to read expected: {}", t.expected_file));

    let actual = if t.plaintext {
        flowmark::fill_text(&input, flowmark::Wrap::Wrap, 88, "", "", 0, None)
    } else {
        fill_markdown(
            &input,
            true,
            88,
            t.semantic,
            t.cleanups,
            t.smartquotes,
            t.ellipses,
            None,
            t.list_spacing,
        )
    };

    if actual != expected {
        let actual_file = t.expected_file.replace(".expected.", ".actual.");
        let actual_path = parity_dir.join(&actual_file);
        std::fs::write(&actual_path, &actual)
            .unwrap_or_else(|_| panic!("Failed to write actual output: {actual_file}"));

        let exp_lines: Vec<&str> = expected.lines().collect();
        let act_lines: Vec<&str> = actual.lines().collect();
        for (i, (e, a)) in exp_lines.iter().zip(act_lines.iter()).enumerate() {
            assert_eq!(
                e,
                a,
                "Parity mismatch in {} ({} mode) at line {}.\n\
                 Full actual output written to: {actual_file}",
                t.input_file,
                t.mode_name,
                i + 1,
            );
        }
        assert_eq!(
            exp_lines.len(),
            act_lines.len(),
            "Line count differs in {} ({} mode). Actual: {actual_file}",
            t.input_file,
            t.mode_name,
        );
    }
}

// =============================================================================
// Corner-cases golden tests: one test per (file, mode) pair.
// Expected output generated by the pinned Python flowmark version (see Cargo.toml).
// =============================================================================

#[test]
fn test_parity_corner_cases_default() {
    run_parity_golden(&GoldenTest {
        input_file: "corner-cases.md",
        expected_file: "corner-cases.expected.default.md",
        mode_name: "default",
        semantic: false,
        cleanups: false,
        smartquotes: false,
        ellipses: false,
        plaintext: false,
        list_spacing: ListSpacing::Preserve,
    });
}

#[test]
fn test_parity_corner_cases_auto() {
    run_parity_golden(&GoldenTest {
        input_file: "corner-cases.md",
        expected_file: "corner-cases.expected.auto.md",
        mode_name: "auto",
        semantic: true,
        cleanups: true,
        smartquotes: true,
        ellipses: true,
        plaintext: false,
        list_spacing: ListSpacing::Preserve,
    });
}

#[test]
fn test_parity_corner_cases_tight() {
    run_parity_golden(&GoldenTest {
        input_file: "corner-cases.md",
        expected_file: "corner-cases.expected.tight.md",
        mode_name: "tight",
        semantic: true,
        cleanups: false,
        smartquotes: false,
        ellipses: false,
        plaintext: false,
        list_spacing: ListSpacing::Tight,
    });
}

#[test]
fn test_parity_corner_cases_loose() {
    run_parity_golden(&GoldenTest {
        input_file: "corner-cases.md",
        expected_file: "corner-cases.expected.loose.md",
        mode_name: "loose",
        semantic: true,
        cleanups: false,
        smartquotes: false,
        ellipses: false,
        plaintext: false,
        list_spacing: ListSpacing::Loose,
    });
}

#[test]
fn test_parity_corner_cases_plaintext() {
    run_parity_golden(&GoldenTest {
        input_file: "corner-cases.md",
        expected_file: "corner-cases.expected.plaintext.md",
        mode_name: "plaintext",
        semantic: false,
        cleanups: false,
        smartquotes: false,
        ellipses: false,
        plaintext: true,
        list_spacing: ListSpacing::Preserve,
    });
}
